[build]
builder = "DOCKERFILE"
watchPatterns = ["app.py", "requirements.txt"]

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
numReplicas = 1

[variables]
OPENAI_API_KEY.sync = "false" 