[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn app:app"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[variables]
OPENAI_API_KEY.sync = "false" 